@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs <<Interface>>

Package Person {
Class Person
Class Name
Class Phone
Class Email
Class Gender
Class Address
Class Block
Class Room
Class MatriculationNumber
Class UniquePersonList
}

Package Event {
Class UniqueEventList
Class Event
Class EventName
Class EventDate
Class Location
Class Description
}

Package StudentGroup {
Class StudentGroup
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ObservableList

ModelManager o--> "1" AddressBook
ModelManager o--> "1" UserPrefs

AddressBook .up.|> ReadOnlyAddressBook
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueEventList
AddressBook *--> "1" UniquePersonList

UniquePersonList o--> "*" Person
Person *---> Block
Person *---> Room
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Gender
Person *---> MatriculationNumber
Person *---> Address

UniqueEventList o--> " * " Event
Event *--> EventName
Event *---> EventDate
Event *---> Location
Event *---> Description
Event -> "*" Person : "attendees"

Person *--->"  *  " StudentGroup
ModelManager ----->"1" Person : " filtered list"
@enduml
